version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    #command: uvicorn APi.main:app --workers 1 --host 0.0.0.0 --port 8080 --log-level debug
    networks:
      - supply-chain-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: projet_supply-chain-elasticsearch-1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - supply-chain-network

networks:
  supply-chain-network: