version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "80:80"
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - supply-chain-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - supply-chain-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - supply-chain-network

networks:
  supply-chain-network: